"apiVersion": "kustomize.config.k8s.io/v1beta1"
"kind": "Kustomization"
"patches":
- "patch": |
    "apiVersion": "v1"
    "kind": "ServiceAccount"
    "metadata":
      "annotations":
        "azure.workload.identity/client-id": "77725ab0-0b79-45b7-be87-92a9606eed17"
        "azure.workload.identity/tenant-id": "721342f3-ed34-4553-93ea-4fbe8f7149eb"
      "name": "kustomize-controller"
  "target":
    "kind": "ServiceAccount"
    "name": "kustomize-controller"
- "patch": |
    "apiVersion": "apps/v1"
    "kind": "Deployment"
    "metadata":
      "name": "kustomize-controller"
    "spec":
      "template":
        "metadata":
          "labels":
            "azure.workload.identity/use": "true"
  "target":
    "kind": "Deployment"
    "name": "kustomize-controller"
- "patch": "[{\"op\":\"add\",\"path\":\"/spec/template/spec/containers/0/args/-\",\"value\":\"--feature-gates=StrictPostBuildSubstitutions=true\"}]"
  "target":
    "kind": "Deployment"
    "name": "kustomize-controller"
"resources":
- "gotk-components.yaml"
- "gotk-sync.yaml"
