apiVersion: v1
kind: Secret
metadata:
    name: qdrant-auth
    namespace: medw
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:V0gxjr5isAobtWS9A9Se8NKWbBiXGevQeQh4lzKDqOuD18Wr4/kCXoGKEQ==,iv:HZHYgc5IQ02+Hew/YMCt/Fu8+Q6t4QBOTQ6r4+CcQ5Y=,tag:4cdqJon7W0WgZJkpRthnsA==,type:str]
    read-only-api-key: ENC[AES256_GCM,data:RknRT1rFvYULFoPQszAJkD0TTVuckz5ej2vTSUqxvxOdHsWbOOaCMTbFZg==,iv:PkMgG7P4J1lPTshwFvoUS8NChxJjedMZfaT43LKa6ZY=,tag:M1pPZo5b2CZQ27ym0jQeOA==,type:str]
sops:
    azure_kv:
        - created_at: "2026-10-01T06:57:04Z"
          enc: JmveSEsA-M8Ta3PBj76_3H8zteHSxzw1xYqTarKfXdFzIXhkASgAfrwP3MtG-Tx1QuaUxg7Ofvbe0g_g19Bf9YtsFTHs5Q38sPJfvwJZbcTV9eCAcZ3HWc6RZOZ_K-I8ZCMCSqPgtaAWqu3x8diP8v-uM5cvOy4hrUkAdKxI4WRuI3tGsm4hnDj0aSCvBw-Ae3g0jte-d9c8Z2pFPFMrlEjS3wGUortgEQXS-5Mqs_qovUrF7b4-VndUXWry_WU6geNmRAhJJay8B9LFe1Cdf6Hab3Jla54gqnqiIXKEVII3oKvMirg8At1kUZk0HXe_3lw4famO_Om8qHLadD6SlO8SRv7Okm1xuYUGe7xzvRFcipoGVQE7_D2QGsQAzYxpUjl8enctykUWUh93eRnRuE5371qyM_3DgZWNvJvKk25D8C6zFmHnQn9NSqVriyxjWYfhN3Suply8w7sE2n3b0fMMdwJVHGkzZc0VHWsgoq1_FLeP4ReNPoNKojH53caU
          name: sops
          vault_url: https://medwdev9528fa20kv.vault.azure.net
          version: 77143d94591f485b93e3b73611b35644
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T06:57:06Z"
    mac: ENC[AES256_GCM,data:1en0jdums9ut71k9M5V8wXEAvYNz6hdcCIwgXinU0cJ+kX/NNL5/MqqPKk1Cq0+5emPs2G59raRQLH9zSGE6bb4IroWFPxdJyiJRTMnFMVGjzRMStxBFGlxgaoB2DkR9P6gkx8jWlhb4i6ekRNZKj//0chmiQ+ErP5k6xuClL7s=,iv:8nmoH7dumG5zzROQd7w1sgp5XvnIoAYsgSKoQU6MEDc=,tag:xx/qXZKbtQm8z9YkB9go4g==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: medw-airflow
    namespace: medw
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:fIb5dWrSz5esm4WcQafseZi8cNVbR97IV7lJ55FhOU+dp30qmMnOpwQEQA==,iv:gL+RmVjKt3enLBjlpZwFr9GcCKXs1IBUSxouBUWY2No=,tag:MZm9Kyt7AOxzjXP3Ey4tSQ==,type:str]
    connection: ENC[AES256_GCM,data:IL5s2pF0vR9lvA7tqMTN6mcseiKThE7yqDAG+J33vLf6sKCJ2qs6Y+m7fvvo1E99sLTzndlR5qhjEMBDkvjwxSo6wJg5bzP5c+iuINL0l36rNzPEgFBqgw==,iv:992am0sgUueDxIm++/wlP+lV1W+Y6rOeM3kxEl2tjV8=,tag:ZgZAiCvsmTFtWKK+AiRuyw==,type:str]
    fernet-key: ENC[AES256_GCM,data:vSi5vofXfAvTtgdJvU3JXacEdVrHkFS5NED5vrADjL7WPD8neDidbZhsiuE=,iv:fsUQuQN9IOpp1iyQHaHqU0oaxHQ5gt3uQMUbHi5RFZY=,tag:N59XRucHNUwHw8YAYcjwRw==,type:str]
    jwt-secret: ENC[AES256_GCM,data:J5TUDsu4HLE3krSaw2JP0rL0LNckG4oFCN+u1/5mVxAxXkumuCaeTfed5Q0e/8yxse4yi58PkqB5qR+XYrkjXE99EkrNvdK98/HGzylGah9FtW0xLic=,iv:cr/JnvANGj/Kl9zoQCWcknjCEFYLIcWsoTP0TiPiUws=,tag:3zQRI8jMv9CGL43FLDR6Zw==,type:str]
    api-secret-key: ENC[AES256_GCM,data:S9Tu0F0YNApoOugdu8F428LxAFdPg8m6DiD+C6mvetQA+awN1gbBv1hxeQ==,iv:hh9w77zK7gpZKKGdZuWhwMq+PKDN/7ZXElMSfZjGM/4=,tag:sCMztwCvCbgC6rWPJ1/PAQ==,type:str]
    admin-password: ENC[AES256_GCM,data:MSvdd1xr9TaK0ijBRzLYYgpufdRbT/nAzlY4oPaDX0NM0YX70LRwogJllg==,iv:JmysVi0yqqwGSF4mR2h/Kq44reCvaTV3EzYL9blSa9A=,tag:jG4PDkuehCZoJSRBFot8vA==,type:str]
sops:
    azure_kv:
        - created_at: "2026-10-01T06:57:04Z"
          enc: JmveSEsA-M8Ta3PBj76_3H8zteHSxzw1xYqTarKfXdFzIXhkASgAfrwP3MtG-Tx1QuaUxg7Ofvbe0g_g19Bf9YtsFTHs5Q38sPJfvwJZbcTV9eCAcZ3HWc6RZOZ_K-I8ZCMCSqPgtaAWqu3x8diP8v-uM5cvOy4hrUkAdKxI4WRuI3tGsm4hnDj0aSCvBw-Ae3g0jte-d9c8Z2pFPFMrlEjS3wGUortgEQXS-5Mqs_qovUrF7b4-VndUXWry_WU6geNmRAhJJay8B9LFe1Cdf6Hab3Jla54gqnqiIXKEVII3oKvMirg8At1kUZk0HXe_3lw4famO_Om8qHLadD6SlO8SRv7Okm1xuYUGe7xzvRFcipoGVQE7_D2QGsQAzYxpUjl8enctykUWUh93eRnRuE5371qyM_3DgZWNvJvKk25D8C6zFmHnQn9NSqVriyxjWYfhN3Suply8w7sE2n3b0fMMdwJVHGkzZc0VHWsgoq1_FLeP4ReNPoNKojH53caU
          name: sops
          vault_url: https://medwdev9528fa20kv.vault.azure.net
          version: 77143d94591f485b93e3b73611b35644
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T06:57:06Z"
    mac: ENC[AES256_GCM,data:1en0jdums9ut71k9M5V8wXEAvYNz6hdcCIwgXinU0cJ+kX/NNL5/MqqPKk1Cq0+5emPs2G59raRQLH9zSGE6bb4IroWFPxdJyiJRTMnFMVGjzRMStxBFGlxgaoB2DkR9P6gkx8jWlhb4i6ekRNZKj//0chmiQ+ErP5k6xuClL7s=,iv:8nmoH7dumG5zzROQd7w1sgp5XvnIoAYsgSKoQU6MEDc=,tag:xx/qXZKbtQm8z9YkB9go4g==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: medw-telemetry
    namespace: medw
type: Opaque
stringData:
    connection-string: ENC[AES256_GCM,data:n9GPl1E59YgTYY+qV20LOMhcFvTFwNclFFUnv4dcXFvN+hpyx3oSyDXDAFeajdWWfENmj1LfjyAtJVmt+UnMJ38OTy5QLqDQfX1PSTD9aqM+EpvXBqLfgBRR3KpIxts7jXiAdG+Km66GIOs04R+U0getCc/ZlMDlB1ipc1HjCaTfHk7A49P3sJO90h2nc2lDKInrYC4BnEyEknvJuXSq5MbnT8HXKDCsdVM3qXS6iCL07oezTWOFiEB6+qBismnrhyZlyWdw8t7u2N6tKQ+bb+c4RkfHJgIXLOH3pTeW+vgKJs0Nt8GgFqdiuonpNHKqc9YzqNDrlGSfBbIh,iv:4aXvblBfxTxF9hyTkcPkJaw2E3TfuKKPww1cyAf+z4g=,tag:0x+jvKV77enqGd59MTziSA==,type:str]
sops:
    azure_kv:
        - created_at: "2026-10-01T06:57:04Z"
          enc: JmveSEsA-M8Ta3PBj76_3H8zteHSxzw1xYqTarKfXdFzIXhkASgAfrwP3MtG-Tx1QuaUxg7Ofvbe0g_g19Bf9YtsFTHs5Q38sPJfvwJZbcTV9eCAcZ3HWc6RZOZ_K-I8ZCMCSqPgtaAWqu3x8diP8v-uM5cvOy4hrUkAdKxI4WRuI3tGsm4hnDj0aSCvBw-Ae3g0jte-d9c8Z2pFPFMrlEjS3wGUortgEQXS-5Mqs_qovUrF7b4-VndUXWry_WU6geNmRAhJJay8B9LFe1Cdf6Hab3Jla54gqnqiIXKEVII3oKvMirg8At1kUZk0HXe_3lw4famO_Om8qHLadD6SlO8SRv7Okm1xuYUGe7xzvRFcipoGVQE7_D2QGsQAzYxpUjl8enctykUWUh93eRnRuE5371qyM_3DgZWNvJvKk25D8C6zFmHnQn9NSqVriyxjWYfhN3Suply8w7sE2n3b0fMMdwJVHGkzZc0VHWsgoq1_FLeP4ReNPoNKojH53caU
          name: sops
          vault_url: https://medwdev9528fa20kv.vault.azure.net
          version: 77143d94591f485b93e3b73611b35644
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T06:57:06Z"
    mac: ENC[AES256_GCM,data:1en0jdums9ut71k9M5V8wXEAvYNz6hdcCIwgXinU0cJ+kX/NNL5/MqqPKk1Cq0+5emPs2G59raRQLH9zSGE6bb4IroWFPxdJyiJRTMnFMVGjzRMStxBFGlxgaoB2DkR9P6gkx8jWlhb4i6ekRNZKj//0chmiQ+ErP5k6xuClL7s=,iv:8nmoH7dumG5zzROQd7w1sgp5XvnIoAYsgSKoQU6MEDc=,tag:xx/qXZKbtQm8z9YkB9go4g==,type:str]
    version: 3.13.3
