apiVersion: v1
kind: Secret
metadata:
    name: qdrant-auth
    namespace: medw
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:XqDqmk2DqNm4kSCqnziJ7iQ3hJ0k7gMtbBORevhlojgugbTYPqqDvxFtIQ==,iv:DbW9/sg1XSRL9NgGxeh1cdyloYaEMvJg5AQCNEChy4A=,tag:vhn0RsQYLYHwYq5W6b+E6A==,type:str]
    read-only-api-key: ENC[AES256_GCM,data:SEUINSlBTKjg9Vy59BP9m1/QAXXFuoyMtiUQhGrSTXTx0y+bS9n5ipbBjQ==,iv:3KcYF9ibtW5s4AmY9A3Z24GSMa95PTTnIIUk6ai1B+I=,tag:ej4KJ8Jzb6+8CL4EaEa+sw==,type:str]
sops:
    azure_kv:
        - created_at: "2026-09-25T03:17:13Z"
          enc: KM5Usam3jCAf4KJhRI68rShRvdzphMpV-iS-FDEmWIGb9QyNutnNMmY84Laivmu8kXZC5qh8F2BN9BbjqnCZC_l5MHqU8OFN0OmKDQdvAZ7X-BjEv9j9_fn4Johb87VeepXbcJkwIq_aHweOKvETwI3Pkj8pSx5NOX9lSAYRKH2VEyJ2uFAex0nlQFya_368phwuCLQk7IVmyL2MIjrbTNDGmLewTyvcQJMio5hpkOHeIyrvA8PKPhbUjkW-1kVPZEftm8Y8cF4b03m1PnDXiqCkAXPrgEk1LsBWc5V8o34OIs2Iv_kH_6974quPI45V1n96JXygCOTWG-zstDydJ_IS8YtcDb264wj4cxq33sbM8qcrQwO2jm02Avf4I2oXmlupIc7grsoRl3Jq0xGpeLlyzyzfto5A6N3LtJQXZrMCi_Eqp0pAQXb-MwKnMkStHAeb1LfasjdUcCvgYJ796wribKuFFryxvhTnJ6NVroH5WsdFUgLupNufK5u89atu
          name: sops
          vault_url: https://medwdev9528fa20kv.vault.azure.net
          version: 77143d94591f485b93e3b73611b35644
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T03:17:15Z"
    mac: ENC[AES256_GCM,data:rKbp/KSsMk2yqeC5XzyrKZNPj1MU2fvVBKMKJxsAiS3hcpzJHJQnM9C6dV2NeEb9a0Kv5+IetIpcZPlFo3wKJsAB05jegYrcqjnFOz63PPomMGDqSGO1PjsUvaZYZ5D5EZrOVaqka/ERA1KDQY6fbnha8bQf0UKtNs+cHLp1S3I=,iv:89fyw+Zw32+2AR20JEFRX8OfPXIsEt/KALcdsFOcB3k=,tag:RSs3P66AS3hkL1q3GpBANg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: medw-airflow
    namespace: medw
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:WowWh7azasMUdGzq22++NqF9GrlqoWcMB/M3Tt6Kx0mM7POf8VHx2iY/Lg==,iv:HIS2fOfGEWQKyNs1aE0NxCYyBKJei0knOdKYEu3rgbQ=,tag:60tto+C5JXRhO699oIDvhw==,type:str]
    connection: ENC[AES256_GCM,data:eGW7SyfVTkSVnxO6KHYsDwYENp6sEUQLiFEeR6fcSemDOARQZNI6dNVCHVog43fc7GcuZuJG/ZUllcKPLTykuKHOhssUjDTEOWZ5mQoVbCTO4VM3tfzNng==,iv:ybGlICNoJU9dFjxOvvI7vGyMREkeS7bbLENHyy0t3KU=,tag:utt8CRnmMS1h3l+AjKuPoA==,type:str]
    fernet-key: ENC[AES256_GCM,data:kivTxY4YhXMYsczpkP/3QNl2o/cfrxlzzYYHoBQCNwokGniHjhN6gPkohr0=,iv:naPcTvRH/aOhoS5jhUbeOtI3l7rnTDmEbKhe757urEQ=,tag:exbMOkTdk8aP1TGX0CbqRQ==,type:str]
    jwt-secret: ENC[AES256_GCM,data:1VbzTccnuuR1Yrje7T6WXl+k+wmmtVvnzk/PPnE0RoF+DnBMBzwi35wNS+lfQpHt3BpxGx18VLXLRU+dS3Id0AQj04v9HNaWllJqHRXOKGqy2HGHdzs=,iv:SdCL6FksHqQlNEs4LXAtH/dzD1z8Ph7KW/O8Eiu99Ns=,tag:2Gs+trz8AhB3bFZLB2lnNw==,type:str]
    api-secret-key: ENC[AES256_GCM,data:VmEjZqGLKrAZvpLWfy4ERqmyga+NErY3AAw9m2EFB/+W3AtCjVV4q1N7Yg==,iv:B3M5BannTMdwC8G1iWAaWtpjLYYhcyBSdgUhM1P/htY=,tag:wbSaGEy5XlbHRPp4k/Xzfw==,type:str]
    admin-password: ENC[AES256_GCM,data:9OhxhwU3En2++Ur2jItAylgPAbPaAGuHfS0rvTwnCLrIBCSyBr/4zN1yPQ==,iv:68QaTRKAU+fOLYsfFaySXEhSiAhCwFH1wEwbmJ97KDk=,tag:+mD/FDmmRshJ+UNmFWvtug==,type:str]
sops:
    azure_kv:
        - created_at: "2026-09-25T03:17:13Z"
          enc: KM5Usam3jCAf4KJhRI68rShRvdzphMpV-iS-FDEmWIGb9QyNutnNMmY84Laivmu8kXZC5qh8F2BN9BbjqnCZC_l5MHqU8OFN0OmKDQdvAZ7X-BjEv9j9_fn4Johb87VeepXbcJkwIq_aHweOKvETwI3Pkj8pSx5NOX9lSAYRKH2VEyJ2uFAex0nlQFya_368phwuCLQk7IVmyL2MIjrbTNDGmLewTyvcQJMio5hpkOHeIyrvA8PKPhbUjkW-1kVPZEftm8Y8cF4b03m1PnDXiqCkAXPrgEk1LsBWc5V8o34OIs2Iv_kH_6974quPI45V1n96JXygCOTWG-zstDydJ_IS8YtcDb264wj4cxq33sbM8qcrQwO2jm02Avf4I2oXmlupIc7grsoRl3Jq0xGpeLlyzyzfto5A6N3LtJQXZrMCi_Eqp0pAQXb-MwKnMkStHAeb1LfasjdUcCvgYJ796wribKuFFryxvhTnJ6NVroH5WsdFUgLupNufK5u89atu
          name: sops
          vault_url: https://medwdev9528fa20kv.vault.azure.net
          version: 77143d94591f485b93e3b73611b35644
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T03:17:15Z"
    mac: ENC[AES256_GCM,data:rKbp/KSsMk2yqeC5XzyrKZNPj1MU2fvVBKMKJxsAiS3hcpzJHJQnM9C6dV2NeEb9a0Kv5+IetIpcZPlFo3wKJsAB05jegYrcqjnFOz63PPomMGDqSGO1PjsUvaZYZ5D5EZrOVaqka/ERA1KDQY6fbnha8bQf0UKtNs+cHLp1S3I=,iv:89fyw+Zw32+2AR20JEFRX8OfPXIsEt/KALcdsFOcB3k=,tag:RSs3P66AS3hkL1q3GpBANg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: medw-telemetry
    namespace: medw
type: Opaque
stringData:
    connection-string: ENC[AES256_GCM,data:qq/EpfEf6C3pWwDYvsili0qexKfIbQDtr4hdGq9ITI32GwqSL/OHFn0VcRfdsMsOLI7rB+tpi6lO75tR/C3Jhk6IR/umINX2g/fo3ESaqjBRQRS+DTxS4tanvKdb42QOCT8WW/0/7oUAKY7fWK3VQoX0xSfux2+rTDJ8zL4kMFdfMLHFs2DDOjYR+on2r2PbV6dUQR4k8gaRIAEPC15tKTvGD5+/6T4ZtAT+YRZV4vN7JhQ1N0atS96zLMcJe0rzzbh9gh/Vy+6p6TmAOqUy7NiXvonYZIwJ/oNAcs/zE8TMXOJv0fB4LDHUT+8YNaoyIb/lff+kg8/lVh70,iv:y2M5EgSwaPBKuowx8+5vp5wEuNGTz3GlR2u8od+gcvM=,tag:ZAIHOElebYcMGvgJ/2NoSw==,type:str]
sops:
    azure_kv:
        - created_at: "2026-09-25T03:17:13Z"
          enc: KM5Usam3jCAf4KJhRI68rShRvdzphMpV-iS-FDEmWIGb9QyNutnNMmY84Laivmu8kXZC5qh8F2BN9BbjqnCZC_l5MHqU8OFN0OmKDQdvAZ7X-BjEv9j9_fn4Johb87VeepXbcJkwIq_aHweOKvETwI3Pkj8pSx5NOX9lSAYRKH2VEyJ2uFAex0nlQFya_368phwuCLQk7IVmyL2MIjrbTNDGmLewTyvcQJMio5hpkOHeIyrvA8PKPhbUjkW-1kVPZEftm8Y8cF4b03m1PnDXiqCkAXPrgEk1LsBWc5V8o34OIs2Iv_kH_6974quPI45V1n96JXygCOTWG-zstDydJ_IS8YtcDb264wj4cxq33sbM8qcrQwO2jm02Avf4I2oXmlupIc7grsoRl3Jq0xGpeLlyzyzfto5A6N3LtJQXZrMCi_Eqp0pAQXb-MwKnMkStHAeb1LfasjdUcCvgYJ796wribKuFFryxvhTnJ6NVroH5WsdFUgLupNufK5u89atu
          name: sops
          vault_url: https://medwdev9528fa20kv.vault.azure.net
          version: 77143d94591f485b93e3b73611b35644
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T03:17:15Z"
    mac: ENC[AES256_GCM,data:rKbp/KSsMk2yqeC5XzyrKZNPj1MU2fvVBKMKJxsAiS3hcpzJHJQnM9C6dV2NeEb9a0Kv5+IetIpcZPlFo3wKJsAB05jegYrcqjnFOz63PPomMGDqSGO1PjsUvaZYZ5D5EZrOVaqka/ERA1KDQY6fbnha8bQf0UKtNs+cHLp1S3I=,iv:89fyw+Zw32+2AR20JEFRX8OfPXIsEt/KALcdsFOcB3k=,tag:RSs3P66AS3hkL1q3GpBANg==,type:str]
    version: 3.13.3
