apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qdrant
  namespace: medw
spec:
  interval: 5m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: deploy/charts/qdrant
      sourceRef:
        kind: GitRepository
        name: medwriter-assist
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  postRenderers:
  - kustomize:
      images:
      - name: qdrant/qdrant
        digest: sha256:057ee3a8da769fe7310dd3537b4dc7583bf87a95ce8ac43c0af5a46bc580d1fc
      patches:
      - target:
          kind: StatefulSet
          name: qdrant
        patch: "apiVersion: apps/v1\nkind: StatefulSet\nmetadata:\n  name: qdrant\n\
          spec:\n  persistentVolumeClaimRetentionPolicy:\n    whenDeleted: Retain\n\
          \    whenScaled: Retain\n  template:\n    spec:\n      containers:\n   \
          \   - name: qdrant\n        livenessProbe:\n          httpGet:\n       \
          \     path: /livez\n            port: 6333\n        startupProbe:\n    \
          \      httpGet:\n            path: /livez\n            port: 6333\n"
