replicas: 1
persistence:
  storageClass: standard
  size: 2Gi
podDisruptionBudget: null
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: '1'
    memory: 2Gi
config:
  replication_factor: 1
  write_consistency_factor: 1
auth:
  enabled: false
snapshots:
  enabled: false
monitoring:
  enabled: false
