trigger:
  branches:
    include:
    - main
  paths:
    include:
    - services
    - pipelines
    - libs
    - db/sql
    - scripts
    - deploy/charts
    - deploy/azure-pipelines
    - deploy/release-behavior.json
    - requirements-dev.txt
    - pyproject.toml
    - Makefile
parameters:
- name: registryHost
  type: string
  default: medwdev9528fa20acr.azurecr.io
- name: azureConnection
  type: string
  default: medw-azure
- name: agentPool
  type: string
  default: ''
- name: buildConcurrency
  type: number
  default: 2
  values:
  - 1
  - 2
- name: releaseBranch
  type: string
  default: main
extends:
  template: _build-template.yml
  parameters:
    registryHost: ${{ parameters.registryHost }}
    azureConnection: ${{ parameters.azureConnection }}
    agentPool: ${{ parameters.agentPool }}
    buildConcurrency: ${{ parameters.buildConcurrency }}
    releaseBranch: ${{ parameters.releaseBranch }}
